### ISSUE TITLE
Registered Services Uptime not working

### ISSUE THREAD

**Issue by cancel-cloud** [JustEverythingTweaked/JET#136]
https://uploadi.ng/SfnGybKJ

**Comment by cancel-cloud** [comment]
Yes, its running: https://uploadi.ng/XlHfqJnk

**Comment by TheFruxz** [comment]
@cancel-cloud could you please add steps, to reproduce this issue?

**Comment by cancel-cloud** [comment]
So i just installed the Beta-Version-13 runnable in the Server plugins folder, than i started the Server and issued the commmand "/service list", multiple times. After I've done that 3 times, JET told me via chat, that the service was running, but not the correct duration.
