### ISSUE TITLE
Interchange fail message displayed twice

### ISSUE THREAD

**Issue by cancel-cloud** [JustEverythingTweaked/JET#138]
The Name **isnt** Taken
https://uploadi.ng/XqzW7KF5

**Comment by TheFruxz** [comment]
Steps to reproduce?

**Comment by TheFruxz** [comment]
@cancel-cloud could you please add steps, to reproduce this issue?

**Comment by cancel-cloud** [comment]
So i just installed the Beta-Version-13 runnable in the Server plugins folder, than i started the Server and issued the commmand "/changeskin Cancelcloud FantaAPI". JET told me via chat, that a critical error accrued, since the name wasn't taken at the moment
