### ISSUE TITLE
Bug: Multiple Sounds play when running /component list

### ISSUE THREAD

**Issue by cancel-cloud** [JustEverythingTweaked/JET#144]
If you run /component list

You hear a sound for every line, wich will explode your ears.
Would be cool to only hear on sound. :D

**Comment by TheFruxz** [comment]
A complete rework of the components interchange is planned, like in the #143. This is currently a little bit behind, but gets also updated in the near future. This issue will be get fixed soon!

**Comment by TheFruxz** [comment]
Build your .jar file with this commit https://github.com/TheFruxz/JET/commit/9af1b7071249ff9a517042ea887c41ac03e9b5c9 to use the fix, without having to rely on the coroutine-update!
