### ISSUE TITLE
Can´t reset Skin

### ISSUE THREAD

**Issue by cancel-cloud** [JustEverythingTweaked/JET#146]
Hey,
so after changing skin to another Player, resetting skin isnt resetting.
Commit:
[b325d611d77f420cf45534a2a7841eb59ef38608](https://github.com/TheFruxz/JET/commit/b325d611d77f420cf45534a2a7841eb59ef38608)
![Screenshot 2022-02-23 143529](https://user-images.githubusercontent.com/76657167/155329918-3261021c-4e5a-4aca-bc6b-909435502b98.png)
)

**Comment by TheFruxz** [comment]
cannot reproduce on current version
