### ISSUE TITLE
Minecraft Chat API

### ISSUE THREAD

**Issue by CoasterFreakDE** [JustEverythingTweaked/JET#205]
It should be possible to easily create texts for the 1.16+ mojang chat format based on the current environment (waterfall or paper).

There should be dsl fuctions for every aspect of the chat api with rgb hex color(static and gradient) support out of the box.
For rgb reference you can take a look at https://github.com/CoasterFreakDE/minecraft-spigot-rgb-chat-support (Feel free to include and/or edit the code for your needs)

Currently the Bungee Chat API supports most of the features but is hard to use ( https://www.spigotmc.org/wiki/the-chat-component-api/ )

To test all vanilla features you can use the following website: https://minecraft.tools/en/tellraw.php

An example dsl text could look like this:
![image](https://user-images.githubusercontent.com/28011628/160414233-b72ad383-cba2-4737-b206-c52d7e8fe138.png)

---

Tasks:
- [ ] Create a multi-plattform compatible structure
- [ ] Create "adapters" for each platform (Paper, Bungee, Velocity)
- [ ] Support common colors, but also a unifying
   - [x] #209
- [ ] Kotlin JSON Support
- [ ] Adventure!
- [ ] ComponentTypes
   - [ ] Formatting
      - [ ] Color support
      - [ ] Hover & Action support
   - [ ] Special Components
      - [ ] Text
      - [ ] Translate
      - [ ] Keybind
      - [ ] Score
      - [ ] Selector
      - [ ] nbt

**Comment by CoasterFreakDE** [comment]
Working code snippet:

```kt
fun copy(text: String): ClickEvent {
    return ClickEvent(ClickEvent.Action.COPY_TO_CLIPBOARD, text)
}

fun Array<BaseComponent>.click(function: () -> ClickEvent) {
    forEach { it.clickEvent = function() }
}

fun Array<BaseComponent>.hover(text: String) {
    forEach { it.hoverEvent = HoverEvent(HoverEvent.Action.SHOW_TEXT, Text(text.build())) }
}

fun text(function: Array<BaseComponent>.() -> Array<BaseComponent>): Array<BaseComponent> {
    return function.invoke(arrayOf())
}

fun text(text: String): Array<BaseComponent> {
    return text.build()
}

fun Array<BaseComponent>.text(text: String): Array<BaseComponent> {
    return this + text.build()
}

fun text(text: String, function: Array<BaseComponent>.() -> Unit): Array<BaseComponent> {
    val message = text.build()
    return message.apply(function)
}
```

Works for hover & click to copy:

```kt
val message: Array<BaseComponent> = text {
        text("#d2dae2Username: ") +
        text("#fbc531${sender.name}") {
            hover("#fbc531Click to copy")
            click {
                copy(sender.name)
            }
        } +
        text(" #d2dae2Password: ") +
        text("#fbc531Hidden") {
            hover("#fbc531Click to copy")
            click {
                copy("ABC123")
            }
        }
    }
    sender.sendMessage(*message)
```

**Comment by TheFruxz** [comment]
Seems like a cool and flexible idea! 👍

**Comment by TheFruxz** [comment]
Tasks:
- [ ] Create a multi-plattform compatible structure
- [ ] Create "adapters" for each platform (Paper, Bungee, Velocity)
- [ ] Kotlin JSON Support
- [ ] Adventure!
- [ ] ComponentTypes
   - [ ] Formatting
      - [ ] Color support
      - [ ] Hover & Action support
   - [ ] Special Components
      - [ ] Text
      - [ ] Translate
      - [ ] Keybind
      - [ ] Score
      - [ ] Selector
      - [ ] nbt
