### ISSUE TITLE
JET doesnt know component name

### ISSUE THREAD

**Issue by cancel-cloud** [JustEverythingTweaked/JET#234]
![Screenshot 2022-04-12 131355](https://user-images.githubusercontent.com/76657167/162948173-9ee6c770-9174-4948-bf55-2d1c8b49faa1.png)
![Screenshot 2022-04-12 131341](https://user-images.githubusercontent.com/76657167/162948178-2a15e969-0c8a-476c-a38e-da672f8417c4.png)

**Comment by TheFruxz** [comment]
Fixed with 92d06e4179c719382dccd750d1bd1aafc419e5c2
